name: kernel

on:
  push:
    paths:
      - '.github/workflows/kernel.yml'
      - 'kernel.sh'
  schedule:
    - cron: 30 6 * * *
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  job_kernel:
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    runs-on: ubuntu-latest
     

    name: Update kernel
    strategy:
      fail-fast: false
      matrix:
        target: [main]
        
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Initialization environment
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Jakarta"
        
    - name: Clone packages
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo  apt-get -qq update
        sudo  apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo  apt-get -qq autoremove --purge
        sudo  apt-get -qq clean
        sudo timedatectl set-timezone 
        sudo  apt-get install megatools
        cd $GITHUB_WORKSPACE
        chmod +x .github/diy/kernel.sh
        git clone -b main https://github.com/cuangky/kernel.git ${{matrix.target}}
        cd ${{matrix.target}}
        git rm -r --cache * >/dev/null 2>&1 &
        #rm -rf `find ./* -maxdepth 0 -type d ! -name "commit"` >/dev/null 2>&1
        $GITHUB_WORKSPACE/.github/diy/kernel.sh
        
    - name: Upload
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
       # [ -e $GITHUB_WORKSPACE/LICENSE ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/${{matrix.target}}
       # [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/${{matrix.target}}
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        git add .
        git commit -am "update $(date +%Y-%m-%d" "%H:%M:%S)"
        git push --force "https://${{ secrets.ACCESS_TOKEN }}@github.com/cuangky/kernel.git" HEAD:${{matrix.target}}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 5
        keep_minimum_runs: 1       
