name: repo_IndoWrt 2

on:
  push:
    paths:
      - '.github/workflows/repo_indowrt_2.yml'
      - 'IndoWrt_2.sh'  
 # schedule:
 #   - cron: 30 6 * * *
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH Actions'
        required: false
        default: 'false'

jobs:
  job_repo:
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    runs-on: ubuntu-latest

    name: Update repo
    strategy:
      fail-fast: false
      matrix:
        target: [main]
        
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Initialization environment
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Jakarta"
        
    - name: Clone packages
      run: |
        docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get -qq update -y
          sudo -E apt-get -qq full-upgrade -y
          sudo -E apt-get -qq install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          echo "status=success" >> ${GITHUB_OUTPUT}

        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        cd $GITHUB_WORKSPACE
        chmod +x .github/diy/IndoWrt_2.sh
        git clone -b main https://github.com/indowrt/repoku.git ${{matrix.target}}
        cd ${{matrix.target}}
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf `find ./* -maxdepth 0 -type d ! -name "diy"` >/dev/null 2>&1
        $GITHUB_WORKSPACE/.github/diy/IndoWrt_2.sh
        

    - name: Upload
      env: 
        INDOWRT_TOKEN: ${{ secrets.INDOWRT_TOKEN }}
      run: |
        [ -e $GITHUB_WORKSPACE/LICENSE ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/${{matrix.target}}
        [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/${{matrix.target}}
        cd $GITHUB_WORKSPACE/${{matrix.target}}
      
        git add . 
        git commit -am "update $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f "https://${{ secrets.INDOWRT_TOKEN }}@github.com/indowrt/repoku.git" HEAD:${{matrix.target}}    
      
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.INDOWRT_TOKEN }}
        repository: indowrt/repoku
        retain_days: 1
        keep_minimum_runs: 1
