name: repo

on:
  push:
    paths:
      - '.github/workflows/repo.yml'
      - 'main.sh'  
  schedule:
    - cron: 0 */12 * * *
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH Actions'
        required: false
        default: 'false'

jobs:
  job_repo:
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    runs-on: ubuntu-latest

    name: Update repo
    strategy:
      fail-fast: false
      matrix:
        target: [main]
        
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Initialization environment
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Jakarta"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x .github/diy/main.sh
        git clone -b main https://github.com/indowrt/indowrt.git ${{matrix.target}}
        cd ${{matrix.target}}
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf `find ./* -maxdepth 0 -type d ! -name "diy"` >/dev/null 2>&1
        $GITHUB_WORKSPACE/.github/diy/${{matrix.target}}.sh
        

    - name: Upload
      env: 
        INDOWRT_TOKEN: ${{ secrets.INDOWRT_TOKEN }}
      run: |
        [ -e $GITHUB_WORKSPACE/LICENSE ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/${{matrix.target}}
        [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README_en.md $GITHUB_WORKSPACE/${{matrix.target}}
        cd $GITHUB_WORKSPACE/${{matrix.target}}
      
        git add . 
        git commit -am "update $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f "https://${{ secrets.INDOWRT_TOKEN }}@github.com/indowrt/indowrt.git" HEAD:${{matrix.target}}    
      
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.INDOWRT_TOKEN }}
        repository: indowrt/indowrt
        retain_days: 1
        keep_minimum_runs: 1
